from typing import Any, Dict, Optional, Union

# System Variables
sender: int = ...
self_id: int = ...
input_data: str = ...

# Storage
storage_str: Dict[str, str] = ...
storage_int: Dict[str, int] = ...

# Basic Operations
def reply(msg: str) -> None: ...
def transfer(to: int, amount: int, currency: int) -> None: ...
def cancel(reason: str) -> None: ...
def exit() -> None: ...

# Extended Functions
def sha256(val: str) -> str: ...
def random(min_val: int, max_val: int) -> int: ...
def get_balance(user: int, currency: int) -> int: ...

# New Functions
def concat(a: str, b: str) -> str: ...
def approve(spender: int, amount: int, currency: int) -> None: ...
def transfer_from(sender: int, recipient: int, amount: int, currency: int) -> Any: ...
def get_currency(currency_id: int) -> Any: ...
def get_transaction(tx_id: int) -> Any: ...
def create_claim(payer: int, amount: int, currency: int, desc: str = None) -> Any: ...
def pay_claim(claim_id: int) -> Any: ...
def cancel_claim(claim_id: int) -> Any: ...
def execute_contract(destination_id: int, input_data: str = None) -> str: ...
def discord_send(guild_id: int, channel_id: int, message: str) -> int: ...
def discord_role_add(user_id: int, guild_id: int, role_id: int) -> int: ...
