from typing import Any, Dict, Optional, Union

# System Variables
sender: int = ...
self_id: int = ...
input_data: str = ...

# Storage
class Storage:
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...

storage: Storage = Storage()
storage_str: Dict[str, str] = ...
storage_int: Dict[str, int] = ...

# Basic Operations
def reply(msg: str) -> None: ...
def transfer(to: int, amount: int, currency: int) -> None: ...
def cancel(reason: str) -> None: ...
def exit() -> None: ...

# Extended Functions
def sha256(val: str) -> str: ...
def random(min_val: int, max_val: int) -> int: ...
def get_balance(user: int, currency: int) -> int: ...
