from typing import Optional

# System Variables
sender: int = ...
self_id: int = ...
input_data: str = ...

# Storage
storage: dict[str, str] = ...

class Currency:
    currency_id: int
    name: str
    symbol: str
    issuer_id: int
    supply: int
    minting_renounced: bool
    delete_requested_at: Optional[int]
    hourly_interest_rate: int
    new_hourly_interest_rate: Optional[int]
    rate_change_requested_at: Optional[int]

class Transaction:
    transfer_id: int
    execution_id: Optional[int]
    source_id: int
    dest_id: int
    currency_id: int
    amount: int
    timestamp: int

class Claim:
    claim_id: int
    claimant_id: int
    payer_id: int
    currency_id: int
    amount: int
    status: str
    created_at: int
    description: Optional[str]

# Basic Operations
def output(msg: str) -> None: ...
def transfer(to: int, amount: int, currency: int) -> None: ...
def cancel(reason: str) -> None: ...
def exit() -> None: ...

# Extended Functions
def sha256(val: str) -> str: ...
def random(min_val: int, max_val: int) -> int: ...
def get_balance(user: int, currency: int) -> int: ...

# New Functions
def concat(a: str, b: str) -> str: ...
def approve(spender: int, amount: int, currency: int) -> None: ...
def transfer_from(sender: int, recipient: int, amount: int, currency: int) -> Transaction: ...
def get_allowance(owner: int, spender: int, currency: int) -> int: ...
def get_currency(currency_id: int) -> Currency: ...
def get_transaction(tx_id: int) -> Transaction: ...
def create_claim(payer: int, amount: int, currency: int, desc: str = None) -> Claim: ...
def pay_claim(claim_id: int) -> Transaction: ...
def cancel_claim(claim_id: int) -> Claim: ...
def execute(destination_id: int, input_data: str = None) -> str: ...
def discord_send(guild_id: int, channel_id: int, message: str) -> int: ...
def discord_role_add(user_id: int, guild_id: int, role_id: int) -> int: ...
def has_role(user_id: int, guild_id: int, role_id: int) -> bool: ...
def length(val: str) -> int: ...
def split(val: str, separator: str) -> list[str]: ...
def to_str(val: int) -> str: ...
def to_int(val: str) -> int: ...
def now() -> int: ...

def swap(from_currency_id: int, to_currency_id: int, amount: int) -> Transaction: ...
def add_liquidity(currency_a_id: int, currency_b_id: int, amount_a: int, amount_b: int) -> int: ...
def remove_liquidity(currency_a_id: int, currency_b_id: int, shares: int) -> list[int]: ...
